### ISSUE TITLE
Issue converting ECS from Yaml to PHP

### ISSUE THREAD

**Issue by u01jmg3** [migrify/migrify#114]
(Continuation of conversation at https://github.com/rectorphp/rector/pull/3761)

---

That's the converter now working for me! I did have an issue with FileSystem complaining about the output directory not being writable but I was able to get around that (I realise that is a Symfony package anyway).

So `rector.yml` converted without issue but I am seeing 2 problems when converting `ecs.yml`.

1. The converter completes but it doesn't convert `"\n"` properly.

   ```yml
   parameters:
       line_ending: "\n"
   ```

   - Output:

    ```php
    $parameters->set('line_ending', '
    ');
    ```

   - Expected:

    ```php
    $parameters->set('line_ending', "\n");
    ```

1. The converter fails to run even though the setting is supported and worked as a Yaml config. Similar for other sniffs. If I remove the `spacing` setting the converter completes without issue.

   ```yml
   services:
       PHP_CodeSniffer\Standards\Generic\Sniffs\Formatting\SpaceAfterNotSniff:
           spacing: 0
   ```
