### ISSUE TITLE
[config-transformer] not all things are transformed

### ISSUE THREAD

**Issue by vladyslavstartsev** [migrify/migrify#207]
first of all thanks for the package. It is really helpful

to see what was not changed I'll provide original and transformed files

```yaml
foo:
    path: /asd/das/{foo}
    controller: Asd\Das
    methods: GET
    requirements:
      foo: '[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}'
```

transformed to

```php
<?php

declare(strict_types=1);

use Asd\Das;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

return static function (RoutingConfigurator $routingConfigurator): void {
    $routingConfigurator->add('foo', '/asd/das/{foo}')
        ->controller(Das::class);
};

```

see that `requirements` and `methods` is missing
