### ISSUE TITLE
[ConfigTransformer] Use ::class over strings, if part of parameters

### ISSUE THREAD

**Issue by TomasVotruba** [migrify/migrify#66]
## Before

```yaml
parameters:
    skip:
        # Only some rules from ControlStructureSpacingSniff are part of PSR-2, skip the rest:
        PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ControlStructureSpacingSniff.SpacingAfterOpenBrace: null
```

## After

```php
 $paremeters->set('skip', [
    \PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ControlStructureSpacingSniff::class . '.SpacingAfterOpenBrace'
]);
```
