### ISSUE TITLE
[ConfigTransformer]  Keep nested args keys

### ISSUE THREAD

**Issue by TomasVotruba** [migrify/migrify#77]
```yaml
services:
    Rector\Core\Rector\Argument\ArgumentDefaultValueReplacerRector:
        $replacesByMethodAndTypes:
            Symfony\Component\Routing\Generator\UrlGeneratorInterface:
                generate:
                    2:
                        -
                            before: true
                            after: Symfony\Component\Routing\Generator\UrlGeneratorInterface
```

Currently, the `2` is silently removed
