### ISSUE TITLE
[YAML to PHP migration] Calls to ref() function is deprecated, use service() instead

### ISSUE THREAD

**Issue by TavoNiievez** [migrify/migrify#94]
Running 

`vendor/bin/config-transformer switch-format config/ --intput-format yaml --output-format php`

prints `ref()` functions calls (deprecated since Symfony 5.1) instead of the `service()` functions. Even with:

`--target-symfony-version 5.1`

For example:
```
services:
    app.menu_builder:
        class: App\Utils\MenuBuilder
        arguments: ["@knp_menu.factory"]
```
results in:
```
    $services->set('app.menu_builder', MenuBuilder::class)
        ->args([ref('knp_menu.factory')]);
```
instead of:
```
    $services->set('app.menu_builder', MenuBuilder::class)
        ->args([service('knp_menu.factory')]);
```
